# -*- coding: utf-8 -*-
"""Misinformation model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDWByY4wPkAfJr6tKKqc-kcRmL4Vegxy
"""

!pip install -U transformers datasets scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    confusion_matrix
)
from sklearn.utils.class_weight import compute_class_weight

from transformers import (
    RobertaTokenizer,
    RobertaForSequenceClassification,
    TrainingArguments,
    Trainer
)

df = pd.read_csv("dataset.csv")

# Remove NaN labels
df = df.dropna(subset=["is_rumor"])
df = df.dropna(subset=["text"])

df = df.reset_index(drop=True)

# Convert labels to int
df["is_rumor"] = df["is_rumor"].astype(int)

print(df["is_rumor"].value_counts())

texts = df["text"].tolist()
labels = df["is_rumor"].tolist()

train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

tokenizer = RobertaTokenizer.from_pretrained("roberta-base")

train_encodings = tokenizer(
    train_texts,
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    val_texts,
    truncation=True,
    padding=True,
    max_length=128
)

class RumorDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = RumorDataset(train_encodings, train_labels)
val_dataset = RumorDataset(val_encodings, val_labels)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(train_labels),
    y=train_labels
)

class_weights = torch.tensor(class_weights, dtype=torch.float)
print("Class weights:", class_weights)

model = RobertaForSequenceClassification.from_pretrained(
    "roberta-base",
    num_labels=2
)

import torch.nn as nn

class WeightedTrainer(Trainer):
    def compute_loss(
        self,
        model,
        inputs,
        return_outputs=False,
        num_items_in_batch=None
    ):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        loss_fct = nn.CrossEntropyLoss(
            weight=class_weights.to(model.device)
        )

        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="binary",
        zero_division=0
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.save_model("misinformation_model")
tokenizer.save_pretrained("misinformation_model")

predictions = trainer.predict(val_dataset)
preds = np.argmax(predictions.predictions, axis=1)

cm = confusion_matrix(val_labels, preds)

plt.figure()
sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

log_history = trainer.state.log_history
df_logs = pd.DataFrame(log_history)

# Extract training loss and validation loss along with epochs
train_losses = []
val_losses = []
epochs_for_plot = []

for log in log_history:
    if "loss" in log and "epoch" in log and "eval_loss" not in log:
        train_losses.append(log["loss"])
        epochs_for_plot.append(log["epoch"])
    if "eval_loss" in log:
        val_losses.append(log["eval_loss"])

print("Epochs for plotting:", epochs_for_plot)
print("Training Loss:", train_losses)
print("Validation Loss:", val_losses)

# Plotting training and validation loss on the same graph
plt.figure(figsize=(10, 6))
plt.plot(epochs_for_plot, train_losses, label="Training Loss", marker='o')
plt.plot(epochs_for_plot, val_losses, label="Validation Loss", marker='x')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training and Validation Loss Curve")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

def predict_post(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    # Move input tensors to the same device as the model
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=1)
    prediction = torch.argmax(probs).item()

    return "Misinformation" if prediction == 1 else "Credible"

# Example
predict_post("Breaking news: Today is danagerous day")

trainer.save_model("misinformation_model")
tokenizer.save_pretrained("misinformation_model")

from google.colab import files
!zip -r misinformation_model.zip misinformation_model
files.download("misinformation_model.zip")

print("Total samples:", len(df))
print("Training samples:", len(train_texts))
print("Validation samples:", len(val_texts))